export const dataRooms = [
    {
        src: 'IMG',
        id: '#000123456',
        name: 'Deluxe A-91234',
        bed: 'Double Bed',
        floor: 'Floor A-1',
        facilities: 'AC, Shower, Double Bed, Towel, Bathup, Coffee Set, LED TV, Wifi',
        rate: '$145/night',
        status: 'Available',
    },
    {
        src: 'IMG',
        id: '#000123456',
        name: 'Deluxe A-91234',
        bed: 'Double Bed',
        floor: 'Floor A-1',
        facilities: 'AC, Shower, Double Bed, Towel, Bathup, Coffee Set, LED TV, Wifi',
        rate: '$145/night',
        status: 'Available',
    },
    {
        src: 'IMG',
        id: '#000123456',
        name: 'Deluxe A-91234',
        bed: 'Double Bed',
        floor: 'Floor A-1',
        facilities: 'AC, Shower, Double Bed, Towel, Bathup, Coffee Set, LED TV, Wifi',
        rate: '$145/night',
        status: 'Available',
    },
    {
        src: 'IMG',
        id: '#000123456',
        name: 'Deluxe A-91234',
        bed: 'Double Bed',
        floor: 'Floor A-1',
        facilities: 'AC, Shower, Double Bed, Towel, Bathup, Coffee Set, LED TV, Wifi',
        rate: '$145/night',
        status: 'Available',
    },
    {
        src: 'IMG',
        id: '#000123456',
        name: 'Deluxe A-91234',
        bed: 'Double Bed',
        floor: 'Floor A-1',
        facilities: 'AC, Shower, Double Bed, Towel, Bathup, Coffee Set, LED TV, Wifi',
        rate: '$145/night',
        status: 'Available',
    },
    {
        src: 'IMG',
        id: '#000123456',
        name: 'Deluxe A-91234',
        bed: 'Double Bed',
        floor: 'Floor A-1',
        facilities: 'AC, Shower, Double Bed, Towel, Bathup, Coffee Set, LED TV, Wifi',
        rate: '$145/night',
        status: 'Available',
    },
]